### ISSUE TITLE
No binary module built

### ISSUE THREAD

**Issue by torquil** [sgorpi/midex8#2]
On Debian Testing, using linux 5.4, I tried to build snd-usb-midex.ko today. I downloaded the linux sources to /usr/src/linux-source-5.4. I have the midex driver sources in ~/src/midex8.

I did the following:

$ cd ~/src/midex8/src/kernel
$ ./build.sh -k /usr/src/linux-source-5.4

and then the build process started. However, I did not get any binary module in src/kernel/sound/usb/midex (still only Makefile and midex.c). The end of the build process log was the following:

`LD [M]  sound/usb/snd-usb-audio.ko
  CC [M]  sound/usb/snd-usbmidi-lib.mod.o
  LD [M]  sound/usb/snd-usbmidi-lib.ko
  CC [M]  sound/usb/usx2y/snd-usb-us122l.mod.o
  LD [M]  sound/usb/usx2y/snd-usb-us122l.ko
  CC [M]  sound/usb/usx2y/snd-usb-usx2y.mod.o
  LD [M]  sound/usb/usx2y/snd-usb-usx2y.ko
  CC [M]  sound/x86/snd-hdmi-lpe-audio.mod.o
  LD [M]  sound/x86/snd-hdmi-lpe-audio.ko
  CC [M]  sound/xen/snd_xen_front.mod.o
  LD [M]  sound/xen/snd_xen_front.ko
  CC [M]  virt/lib/irqbypass.mod.o
  LD [M]  virt/lib/irqbypass.ko
make[1]: Leaving directory '/home/torquil/src/midex8/src/kernel'
Running ./scripts/checkpatch.pl:
WARNING: Missing or malformed SPDX-License-Identifier tag in line 1
#1: FILE: /home/torquil/src/midex8/src/kernel/sound/usb/midex/midex.c:1:
+/*

total: 0 errors, 1 warnings, 1693 lines checked

NOTE: For some of the reported defects, checkpatch may be able to
      mechanically convert to the typical style using --fix or --fix-inplace.

/home/torquil/src/midex8/src/kernel/sound/usb/midex/midex.c has style problems, please review.

NOTE: If any of the errors are false positives, please report
      them to the maintainer, see CHECKPATCH in MAINTAINERS.
make[1]: Entering directory '/home/torquil/src/midex8/src/kernel'
  GEN     Makefile
  CALL    /usr/src/linux-source-5.4/scripts/checksyscalls.sh
  CALL    /usr/src/linux-source-5.4/scripts/atomic/check-atomics.sh
  DESCEND  objtool
  Building modules, stage 2.
  MODPOST 3567 modules
make[1]: Leaving directory '/home/torquil/src/midex8/src/kernel'`

According to the build log, I expected that the module was build, since it ways "0 errors".

Best regards,
Torquil Sørensen

**Comment by sgorpi** [comment]
Hi, thanks for the interest.

I've updated the build script. It now only depends on kernel headers and not complete source anymore. That should lighten the build process significantly. The warning you saw was from a checkpatch.pl script that checks code style. In the recently pushed update I've hiden that behind a commandline argument.
The other update in that push is a different way of building the module - it now only depends on the kernel headers. The 'make' statement is therefore also slightly different and will only build the module itself. Hope that make the output easier to understand. 
Other than that I indeed see no evidence of the build failing. Thus, if indeed the build succeeds the module should be located in <midex8 repository>/src/kernel/sound/usb/midex/ 

Let me know if it works now, or if you run into anything else!
Sgorpi
