### ISSUE TITLE
Implicit declaration of function 'strlcpy'

### ISSUE THREAD

**Issue by OzzelotCZ** [sgorpi/midex8#7]
It appears the Linux kernel has recently dropped the strlcpy function, causing the build to fail on newer kernels as follows:

`make: Entering directory '/usr/lib/modules/6.9.3-arch1-1/build'`
`  CC [M]  /home/ozzelot/src/midex8/src/kernel/sound/usb/midex/midex.o`
`/home/ozzelot/src/midex8/src/kernel/sound/usb/midex/midex.c: In function ‘sb_midex_init_rawmidi’:`
`/home/ozzelot/src/midex8/src/kernel/sound/usb/midex/midex.c:1392:9: error: implicit declaration of function ‘strlcpy’;`
`did you mean ‘strncpy’? [-Wimplicit-function-declaration]`
` 1392 |         strlcpy(rmidi->name, midex->card->shortname, sizeof(rmidi->name));`
`      |         ^~~~~~~`
`      |         strncpy`

**Comment by sgorpi** [comment]
Thanks for reporting, I haven't upgraded in a while ;) I've pushed an update, moving all to strscpy. Please check if that works for you and let me know!

**Comment by OzzelotCZ** [comment]
Works great with my Midex 3 (also, thanks for merging those changes).
